using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Controls;

[GenerateTypedNameReferences]
public sealed partial class JASChargeCard : Control
{
    public JASChargeCard(string label, string description)
    {
        RobustXamlLoader.Load(this);

        this.ChargeLabel.Text = label;
        this.ChargeDesc.Text = description;
    }
}
