using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Controls;

[GenerateTypedNameReferences]
public sealed partial class JASChargeCategoryButton : Control
{
    public JASChargeCategoryButton(string label)
    {
        RobustXamlLoader.Load(this);

        this.ChargeCategoryButton.Text = label;
    }
}
